In [19]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [24]:
data = pd.read_csv('/content/credit.csv')
data.head()

ID  Customer_ID  Month           Name   Age          SSN Occupation  \
0  5634         3392      1  Aaron Maashoh  23.0  821000265.0  Scientist   
1  5635         3392      2  Aaron Maashoh  23.0  821000265.0  Scientist   
2  5636         3392      3  Aaron Maashoh  23.0  821000265.0  Scientist   
3  5637         3392      4  Aaron Maashoh  23.0  821000265.0  Scientist   
4  5638         3392      5  Aaron Maashoh  23.0  821000265.0  Scientist   

   Annual_Income  Monthly_Inhand_Salary  Num_Bank_Accounts  ...  Credit_Mix  \
0       19114.12            1824.843333                3.0  ...        Good   
1       19114.12            1824.843333                3.0  ...        Good   
2       19114.12            1824.843333                3.0  ...        Good   
3       19114.12            1824.843333                3.0  ...        Good   
4       19114.12            1824.843333                3.0  ...        Good   

   Outstanding_Debt  Credit_Utilization_Ratio Credit_History_Age  \
0            809.98                 26.822620              265.0   
1            809.98                 31.944960              266.0   
2            809.98                 28.609352              267.0   
3            809.98                 31.377862              268.0   
4            809.98                 24.797347              269.0   

   Payment_of_Min_Amount  Total_EMI_per_month  Amount_invested_monthly  \
0                     No            49.574949                 21.46538   
1                     No            49.574949                 21.46538   
2                     No            49.574949                 21.46538   
3                     No            49.574949                 21.46538   
4                     No            49.574949                 21.46538   

                  Payment_Behaviour Monthly_Balance  Credit_Score  
0   High_spent_Small_value_payments      312.494089          Good  
1    Low_spent_Large_value_payments      284.629162          Good  
2   Low_spent_Medium_value_payments      331.209863          Good  
3    Low_spent_Small_value_payments      223.451310          Good  
4  High_spent_Medium_value_payments      341.489231          Good  

[5 rows x 28 columns]

**Loading the 3 datasets**

In [25]:
tr_data= pd.read_csv('/content/train_data.csv')
tr_data.head()

Age  Occupation  Annual_Income  Monthly_Inhand_Salary  Num_Bank_Accounts  \
0  21.0          12      33643.760            2835.646667               10.0   
1  16.0          12      18507.720            1761.310000                8.0   
2  51.0           1      12221.185             853.432083                3.0   
3  23.0          13      20538.770            1957.564167                8.0   
4  35.0           9     106030.050            8628.837500                7.0   

   Num_Credit_Card  Interest_Rate  Num_of_Loan  Type_of_Loan  \
0              8.0           17.0          2.0          3586   
1              5.0           30.0          2.0           509   
2              5.0           18.0          1.0           511   
3             10.0           23.0          6.0           170   
4              3.0           14.0          3.0          4412   

   Delay_from_due_date  ...  Outstanding_Debt  Credit_Utilization_Ratio  \
0                 54.0  ...           2379.75                 37.307187   
1                 29.0  ...           1716.82                 31.813185   
2                 29.0  ...           1155.33                 24.272231   
3                 15.0  ...           2708.55                 28.549148   
4                 12.0  ...            136.53                 27.469387   

   Credit_History_Age  Payment_of_Min_Amount  Total_EMI_per_month  \
0               165.0                      2            36.681715   
1                97.0                      2            27.394667   
2               387.0                      2             6.298573   
3               147.0                      2            76.544155   
4               123.0                      2           136.493245   

   Amount_invested_monthly  Payment_Behaviour  Monthly_Balance  Credit_Score  \
0                35.940161                  2       428.922865             2   
1                25.337112                  0       358.352246             1   
2                28.145892                  3       320.898743             2   
3                58.948238                  4       295.592913             1   
4                80.592270                  3       575.262681             2   

   Credit_Score_Numeric  
0                     1  
1                     0  
2                     1  
3                     0  
4                     1  

[5 rows x 24 columns]

In [26]:
ts_data= pd.read_csv('/content/test_data.csv')
ts_data.head()

Age  Occupation  Annual_Income  Monthly_Inhand_Salary  Num_Bank_Accounts  \
0  39.0           2      64427.300            5075.941667                3.0   
1  28.0           8      23956.270            1773.355833                3.0   
2  21.0           3       9831.865             557.322083                8.0   
3  36.0           1      52979.400            4366.950000                9.0   
4  40.0           3       7023.160             767.263333                7.0   

   Num_Credit_Card  Interest_Rate  Num_of_Loan  Type_of_Loan  \
0              4.0            5.0          2.0          1548   
1              7.0           12.0          3.0          1425   
2             10.0           22.0          7.0           554   
3              8.0           25.0          6.0          2528   
4              3.0           10.0          3.0          3462   

   Delay_from_due_date  ...  Outstanding_Debt  Credit_Utilization_Ratio  \
0                 10.0  ...           1265.70                 30.712426   
1                 10.0  ...            893.87                 25.180476   
2                 15.0  ...           1804.50                 29.246520   
3                 38.0  ...           2861.75                 24.843688   
4                 12.0  ...            335.30                 22.375146   

   Credit_History_Age  Payment_of_Min_Amount  Total_EMI_per_month  \
0               189.0                      0           104.460342   
1               170.0                      2            46.975654   
2               242.0                      2            55.417854   
3               101.0                      2           252.902066   
4               219.0                      2            17.089843   

   Amount_invested_monthly  Payment_Behaviour  Monthly_Balance  Credit_Score  \
0                46.702152                  1       569.177598             0   
1                30.058369                  1       348.032357             2   
2                14.162537                  5       263.782556             1   
3                77.415969                  5       323.722165             1   
4                12.029296                  2       302.237163             2   

   Credit_Score_Numeric  
0                     2  
1                     1  
2                     0  
3                     0  
4                     1  

[5 rows x 24 columns]

In [27]:
val_data= pd.read_csv('/content/val_data.csv')
val_data.head()

Age  Occupation  Annual_Income  Monthly_Inhand_Salary  Num_Bank_Accounts  \
0  16.0           4      39277.220            3117.101667                7.0   
1  49.0           4     116224.680            9873.390000                0.0   
2  44.0           9      53860.980            4260.415000                4.0   
3  42.0           4      43623.840            3592.320000                7.0   
4  25.0          14      16293.385            1145.782083                2.0   

   Num_Credit_Card  Interest_Rate  Num_of_Loan  Type_of_Loan  \
0              7.0           27.0          5.0           264   
1              3.0            8.0          1.0          3593   
2              7.0           15.0          0.0          2558   
3              7.0           23.0          6.0            28   
4              1.0            6.0          0.0          2558   

   Delay_from_due_date  ...  Outstanding_Debt  Credit_Utilization_Ratio  \
0                 41.0  ...           2801.32                 37.467331   
1                 10.0  ...           1388.02                 26.642829   
2                 17.0  ...           1356.10                 30.051513   
3                 23.0  ...           1924.15                 36.237550   
4                  3.0  ...           1189.57                 24.447542   

   Credit_History_Age  Payment_of_Min_Amount  Total_EMI_per_month  \
0                59.0                      2            88.280715   
1               390.0                      1            59.586054   
2               189.0                      2             0.000000   
3               121.0                      2           142.366770   
4               240.0                      1             0.000000   

   Amount_invested_monthly  Payment_Behaviour  Monthly_Balance  Credit_Score  \
0                64.807265                  1       368.216327             1   
1                75.607911                  4       391.256219             2   
2                39.985196                  0       626.056304             2   
3                29.750733                  0       427.114498             1   
4                28.429557                  4       324.631627             0   

   Credit_Score_Numeric  
0                     0  
1                     1  
2                     1  
3                     0  
4                     2  

[5 rows x 24 columns]

**Feature Engineering**

In [30]:
# Create interaction features (e.g., multiplying two numerical features)
def create_interaction_features(data):
    data['Income_Utilization'] = data['Annual_Income'] * data['Credit_Utilization_Ratio']
    data['Debt_to_Income'] = data['Outstanding_Debt'] / (data['Annual_Income'] + 1)
    return data

# Apply to all datasets
train_data = create_interaction_features(tr_data)
val_data = create_interaction_features(val_data)
test_data = create_interaction_features(ts_data)

In [32]:
 #Binning Age into categories
def bin_age(data):
    data['Age_Bin'] = pd.cut(data['Age'], bins=[18, 30, 40, 50, 60, 100], labels=['18-30', '30-40', '40-50', '50-60', '60+'])
    return data

# Apply to all datasets
train_data = bin_age(tr_data)
val_data = bin_age(val_data)
test_data = bin_age(ts_data)

In [33]:
# Log transform to handle skewed data
def log_transform_skewed_features(data):
    data['Log_Outstanding_Debt'] = np.log1p(data['Outstanding_Debt'])
    data['Log_Annual_Income'] = np.log1p(data['Annual_Income'])
    return data

# Apply to all datasets
train_data = log_transform_skewed_features(tr_data)
val_data = log_transform_skewed_features(val_data)
test_data = log_transform_skewed_features(ts_data)

**One hot encoding**

In [34]:
# Apply one-hot encoding to categorical variables (drop_first=True to avoid multicollinearity)
train_data_encoded = pd.get_dummies(train_data, drop_first=True)
val_data_encoded = pd.get_dummies(val_data, drop_first=True)
test_data_encoded = pd.get_dummies(test_data, drop_first=True)

# Ensure consistent columns across all datasets
common_cols = train_data_encoded.columns.intersection(val_data_encoded.columns).intersection(test_data_encoded.columns)

# Filter all datasets to keep only common columns
train_data_encoded = train_data_encoded[common_cols]
val_data_encoded = val_data_encoded[common_cols]
test_data_encoded = test_data_encoded[common_cols]

**Modelling**

In [35]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report

# Define features and target variable
X_train = train_data_encoded.drop(columns=['Credit_Score'])
y_train = train_data_encoded['Credit_Score']

X_val = val_data_encoded.drop(columns=['Credit_Score'])
y_val = val_data_encoded['Credit_Score']

X_test = test_data_encoded.drop(columns=['Credit_Score'])
y_test = test_data_encoded['Credit_Score']

In [36]:
# Define models
models = {
    'KNN': KNeighborsClassifier(),
    'Logistic Regression': LogisticRegression(max_iter=1000),
    'Random Forest': RandomForestClassifier(),
    'Decision Tree': DecisionTreeClassifier(),
    'SVM': SVC()
}

In [39]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report

# Dictionary to store model performance
model_performance = {}

# Function to evaluate a model and store its performance
def evaluate_model(model, X_train, y_train, X_val, y_val, model_name):
    model.fit(X_train, y_train)  # Train the model
    y_pred_val = model.predict(X_val)  # Predictions on validation data

    # Compute metrics
    accuracy = accuracy_score(y_val, y_pred_val)
    precision = precision_score(y_val, y_pred_val, average='weighted')
    recall = recall_score(y_val, y_pred_val, average='weighted')
    f1 = f1_score(y_val, y_pred_val, average='weighted')
    conf_matrix = confusion_matrix(y_val, y_pred_val)
    class_report = classification_report(y_val, y_pred_val, output_dict=True)

    # Store metrics in dictionary
    model_performance[model_name] = {
        'accuracy': accuracy,
        'precision': precision,
        'recall': recall,
        'f1_score': f1,
        'confusion_matrix': conf_matrix,
        'classification_report': class_report
    }


In [40]:
# Evaluate each model and store its performance
for model_name, model in models.items():
    evaluate_model(model, X_train, y_train, X_val, y_val, model_name)

# Display the performance for each model
for model_name, performance in model_performance.items():
    print(f"\nModel: {model_name}")
    print(f"Accuracy: {performance['accuracy']}")
    print(f"Precision: {performance['precision']}")
    print(f"Recall: {performance['recall']}")
    print(f"F1-Score: {performance['f1_score']}")
    print(f"Confusion Matrix:\n{performance['confusion_matrix']}")
    print(f"Classification Report: {performance['classification_report']}")

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(



Model: KNN
Accuracy: 0.4941063596491228
Precision: 0.487645492671337
Recall: 0.4941063596491228
F1-Score: 0.4902788152215909
Confusion Matrix:
[[ 593  377 1611]
 [ 553 1611 1859]
 [1327 1655 5006]]
Classification Report: {'0': {'precision': 0.2397897290739992, 'recall': 0.22975590856257264, 'f1-score': 0.23466561139691333, 'support': 2581.0}, '1': {'precision': 0.44221795223716714, 'recall': 0.4004474272930649, 'f1-score': 0.42029741716671015, 'support': 4023.0}, '2': {'precision': 0.5906087777253421, 'recall': 0.6266900350525789, 'f1-score': 0.6081146744412051, 'support': 7988.0}, 'accuracy': 0.4941063596491228, 'macro avg': {'precision': 0.42420548634550287, 'recall': 0.4189644569694055, 'f1-score': 0.4210259010016095, 'support': 14592.0}, 'weighted avg': {'precision': 0.487645492671337, 'recall': 0.4941063596491228, 'f1-score': 0.4902788152215909, 'support': 14592.0}}

Model: Logistic Regression
Accuracy: 0.6010827850877193
Precision: 0.5591157193999592
Recall: 0.6010827850877193
F

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:14

**Selecting best model**

In [41]:
# Assuming 'Random Forest' performed best based on validation metrics
best_model_name = 'Random Forest'
best_model = models[best_model_name]

# Train the best model on full training data and evaluate on the test set
best_model.fit(X_train, y_train)
y_pred_test = best_model.predict(X_test)

# Calculate metrics on the test set
accuracy_test = accuracy_score(y_test, y_pred_test)
precision_test = precision_score(y_test, y_pred_test, average='weighted')
recall_test = recall_score(y_test, y_pred_test, average='weighted')
f1_test = f1_score(y_test, y_pred_test, average='weighted')
conf_matrix_test = confusion_matrix(y_test, y_pred_test)

In [43]:
 #Print out the test metrics
print(f"\nTest Set Performance for {best_model_name}:")
print(f"Test Accuracy: {accuracy_test}")
print(f"Test Precision: {precision_test}")
print(f"Test Recall: {recall_test}")
print(f"Test F1-score: {f1_test}")
print(f"Test Confusion Matrix:\n{conf_matrix_test}")


Test Set Performance for Random Forest:
Test Accuracy: 0.9999314739943809
Test Precision: 0.9999314825579907
Test Recall: 0.9999314739943809
Test F1-score: 0.9999314693304513
Test Confusion Matrix:
[[2517    0    1]
 [   0 4074    0]
 [   0    0 8001]]
